### PR TITLE
c++ ver added * and # support

### PR DESCRIPTION
**Pull request by 84ds84d8s**

### CODE REVIEW

**Comment by 84ds84d8s** [comment]
multiply and divide removed as c++ seem not to support extended ascii

**Review by eric15342335 — CHANGES_REQUESTED** [review]
This file requires correct indentation adjustments.

**Comment by 84ds84d8s** [comment]
fixed the indentation, but 2 pylint test still failing

**Comment by eric15342335** [comment]
> fixed the indentation, but 2 pylint test still failing

it's irrelevant, pylint only test for python files

**Comment by 84ds84d8s** [comment]
is there any more changes required

**Review by eric15342335 — APPROVED** [review]

**Comment by 84ds84d8s** [comment]
should i squash or rebase

**Pull request merged**
